// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#pragma once

#include "SchemaJson.h" // autogenerated header

#include <string>
#include <unordered_map>

namespace Microsoft
{
    namespace glTF
    {
        namespace GLTFSchema
        {
            constexpr const char* ROOT_GLTF_SCHEMA = "glTF.schema.json";
            const std::unordered_map<std::string, std::string> GLTF_SCHEMA_MAP = Microsoft::glTF::SchemaJson::GLTF_SCHEMA_MAP;
        }
    }
}