name: Release/2.0.0 - CI

on:
  push:
    branches: [ "Release/2.0.0" ]
  pull_request:
    branches: [ "Release/2.0.0" ]

permissions:
  contents: read

jobs:
  build-windows:
    uses: ./.github/workflows/windows.yml
    with:
      cmake-version: '4.2.7'
      platforms: "['x64', 'Win32', 'ARM64']"
      configurations: "['RelWithDebInfo', 'Debug']"

  build-macos:
    uses: ./.github/workflows/macos.yml
    with:
      cmake-version: '3.31.0'
      platforms: "['macOS']"
      configurations: "['RelWithDebInfo', 'Debug']"

  build-ios:
    uses: ./.github/workflows/ios.yml
    with:
      cmake-version: '3.31.0'
      platforms: "['OS', 'SIMULATOR64']"
      configurations: "['RelWithDebInfo', 'Debug']"

  build-android:
    uses: ./.github/workflows/android.yml
    with:
      cmake-version: '3.31.0'
      platforms: "['armeabi-v7a', 'arm64-v8a', 'x86_64']"
      configurations: "['RelWithDebInfo', 'Debug']"

  build-linux:
    uses: ./.github/workflows/linux.yml
    with:
      cmake-version: '3.31.0'
      platforms: "['Linux']"
      configurations: "['RelWithDebInfo', 'Debug']"

  sanitizer:
    uses: ./.github/workflows/sanitizer.yml
    with:
      cmake-version: '3.31.0'
