name: 'sanitizer tests'

on:
  workflow_call:
    inputs:
      cmake-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
            submodules: 'true'

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2
        with:
            cmake-version: ${{ inputs.cmake-version }}

      - name: Install Clang
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y clang lld

      - name: CMake Configure
        run: >
          cmake -G "Unix Makefiles"
          -B ./Built/Int/cmake_Linux_Sanitizer
          -D CMAKE_BUILD_TYPE=Debug
          -D CMAKE_C_COMPILER=clang
          -D CMAKE_CXX_COMPILER=clang++
          -D CMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
          -D CMAKE_C_FLAGS="-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
          -D CMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined"
          -D CMAKE_SHARED_LINKER_FLAGS="-fsanitize=address,undefined"
          -D ENABLE_SAMPLES=OFF
          .

      - name: CMake Build
        run: cmake --build . --target install --config Debug
        working-directory: ./Built/Int/cmake_Linux_Sanitizer

      - name: Running Unit Tests
        run: ./GLTFSDK.Test --gtest_output=xml:GLTFSDK.Test.Sanitizer.log
        working-directory: ./Built/Out/Linux/Debug/GLTFSDK.Test
        env:
          ASAN_OPTIONS: "detect_leaks=0:halt_on_error=1"
          UBSAN_OPTIONS: "print_stacktrace=1:halt_on_error=1"

      - uses: actions/upload-artifact@v4
        name: "Upload test results"
        if: always()
        with:
            name: GLTFSDK.Test.Sanitizer
            path: ${{ github.workspace }}/Built/Out/Linux/Debug/GLTFSDK.Test/GLTFSDK.Test.Sanitizer.log
